// Code generated by protoc-gen-go. DO NOT EDIT.
// source: job.proto

package model

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Job struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Owner                string   `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{0}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Job) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Job) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Job) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type CreateJobReq struct {
	Job                  *Job     `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJobReq) Reset()         { *m = CreateJobReq{} }
func (m *CreateJobReq) String() string { return proto.CompactTextString(m) }
func (*CreateJobReq) ProtoMessage()    {}
func (*CreateJobReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{1}
}

func (m *CreateJobReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobReq.Unmarshal(m, b)
}
func (m *CreateJobReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobReq.Marshal(b, m, deterministic)
}
func (m *CreateJobReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobReq.Merge(m, src)
}
func (m *CreateJobReq) XXX_Size() int {
	return xxx_messageInfo_CreateJobReq.Size(m)
}
func (m *CreateJobReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobReq proto.InternalMessageInfo

func (m *CreateJobReq) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type CreateJobRes struct {
	Job                  *Job     `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJobRes) Reset()         { *m = CreateJobRes{} }
func (m *CreateJobRes) String() string { return proto.CompactTextString(m) }
func (*CreateJobRes) ProtoMessage()    {}
func (*CreateJobRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{2}
}

func (m *CreateJobRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobRes.Unmarshal(m, b)
}
func (m *CreateJobRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobRes.Marshal(b, m, deterministic)
}
func (m *CreateJobRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobRes.Merge(m, src)
}
func (m *CreateJobRes) XXX_Size() int {
	return xxx_messageInfo_CreateJobRes.Size(m)
}
func (m *CreateJobRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobRes proto.InternalMessageInfo

func (m *CreateJobRes) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type UpdateJobReq struct {
	Job                  *Job     `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateJobReq) Reset()         { *m = UpdateJobReq{} }
func (m *UpdateJobReq) String() string { return proto.CompactTextString(m) }
func (*UpdateJobReq) ProtoMessage()    {}
func (*UpdateJobReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{3}
}

func (m *UpdateJobReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateJobReq.Unmarshal(m, b)
}
func (m *UpdateJobReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateJobReq.Marshal(b, m, deterministic)
}
func (m *UpdateJobReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateJobReq.Merge(m, src)
}
func (m *UpdateJobReq) XXX_Size() int {
	return xxx_messageInfo_UpdateJobReq.Size(m)
}
func (m *UpdateJobReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateJobReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateJobReq proto.InternalMessageInfo

func (m *UpdateJobReq) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type UpdateJobRes struct {
	Job                  *Job     `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateJobRes) Reset()         { *m = UpdateJobRes{} }
func (m *UpdateJobRes) String() string { return proto.CompactTextString(m) }
func (*UpdateJobRes) ProtoMessage()    {}
func (*UpdateJobRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{4}
}

func (m *UpdateJobRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateJobRes.Unmarshal(m, b)
}
func (m *UpdateJobRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateJobRes.Marshal(b, m, deterministic)
}
func (m *UpdateJobRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateJobRes.Merge(m, src)
}
func (m *UpdateJobRes) XXX_Size() int {
	return xxx_messageInfo_UpdateJobRes.Size(m)
}
func (m *UpdateJobRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateJobRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateJobRes proto.InternalMessageInfo

func (m *UpdateJobRes) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type ReadJobReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadJobReq) Reset()         { *m = ReadJobReq{} }
func (m *ReadJobReq) String() string { return proto.CompactTextString(m) }
func (*ReadJobReq) ProtoMessage()    {}
func (*ReadJobReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{5}
}

func (m *ReadJobReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadJobReq.Unmarshal(m, b)
}
func (m *ReadJobReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadJobReq.Marshal(b, m, deterministic)
}
func (m *ReadJobReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadJobReq.Merge(m, src)
}
func (m *ReadJobReq) XXX_Size() int {
	return xxx_messageInfo_ReadJobReq.Size(m)
}
func (m *ReadJobReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadJobReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadJobReq proto.InternalMessageInfo

func (m *ReadJobReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadJobRes struct {
	Job                  *Job     `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadJobRes) Reset()         { *m = ReadJobRes{} }
func (m *ReadJobRes) String() string { return proto.CompactTextString(m) }
func (*ReadJobRes) ProtoMessage()    {}
func (*ReadJobRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{6}
}

func (m *ReadJobRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadJobRes.Unmarshal(m, b)
}
func (m *ReadJobRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadJobRes.Marshal(b, m, deterministic)
}
func (m *ReadJobRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadJobRes.Merge(m, src)
}
func (m *ReadJobRes) XXX_Size() int {
	return xxx_messageInfo_ReadJobRes.Size(m)
}
func (m *ReadJobRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadJobRes.DiscardUnknown(m)
}

var xxx_messageInfo_ReadJobRes proto.InternalMessageInfo

func (m *ReadJobRes) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type DeleteJobReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteJobReq) Reset()         { *m = DeleteJobReq{} }
func (m *DeleteJobReq) String() string { return proto.CompactTextString(m) }
func (*DeleteJobReq) ProtoMessage()    {}
func (*DeleteJobReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{7}
}

func (m *DeleteJobReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteJobReq.Unmarshal(m, b)
}
func (m *DeleteJobReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteJobReq.Marshal(b, m, deterministic)
}
func (m *DeleteJobReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteJobReq.Merge(m, src)
}
func (m *DeleteJobReq) XXX_Size() int {
	return xxx_messageInfo_DeleteJobReq.Size(m)
}
func (m *DeleteJobReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteJobReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteJobReq proto.InternalMessageInfo

func (m *DeleteJobReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteJobRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteJobRes) Reset()         { *m = DeleteJobRes{} }
func (m *DeleteJobRes) String() string { return proto.CompactTextString(m) }
func (*DeleteJobRes) ProtoMessage()    {}
func (*DeleteJobRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{8}
}

func (m *DeleteJobRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteJobRes.Unmarshal(m, b)
}
func (m *DeleteJobRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteJobRes.Marshal(b, m, deterministic)
}
func (m *DeleteJobRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteJobRes.Merge(m, src)
}
func (m *DeleteJobRes) XXX_Size() int {
	return xxx_messageInfo_DeleteJobRes.Size(m)
}
func (m *DeleteJobRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteJobRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteJobRes proto.InternalMessageInfo

func (m *DeleteJobRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ListJobsReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListJobsReq) Reset()         { *m = ListJobsReq{} }
func (m *ListJobsReq) String() string { return proto.CompactTextString(m) }
func (*ListJobsReq) ProtoMessage()    {}
func (*ListJobsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{9}
}

func (m *ListJobsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListJobsReq.Unmarshal(m, b)
}
func (m *ListJobsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListJobsReq.Marshal(b, m, deterministic)
}
func (m *ListJobsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListJobsReq.Merge(m, src)
}
func (m *ListJobsReq) XXX_Size() int {
	return xxx_messageInfo_ListJobsReq.Size(m)
}
func (m *ListJobsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListJobsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListJobsReq proto.InternalMessageInfo

type ListJobsRes struct {
	Job                  *Job     `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListJobsRes) Reset()         { *m = ListJobsRes{} }
func (m *ListJobsRes) String() string { return proto.CompactTextString(m) }
func (*ListJobsRes) ProtoMessage()    {}
func (*ListJobsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{10}
}

func (m *ListJobsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListJobsRes.Unmarshal(m, b)
}
func (m *ListJobsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListJobsRes.Marshal(b, m, deterministic)
}
func (m *ListJobsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListJobsRes.Merge(m, src)
}
func (m *ListJobsRes) XXX_Size() int {
	return xxx_messageInfo_ListJobsRes.Size(m)
}
func (m *ListJobsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListJobsRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListJobsRes proto.InternalMessageInfo

func (m *ListJobsRes) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

func init() {
	proto.RegisterType((*Job)(nil), "model.Job")
	proto.RegisterType((*CreateJobReq)(nil), "model.CreateJobReq")
	proto.RegisterType((*CreateJobRes)(nil), "model.CreateJobRes")
	proto.RegisterType((*UpdateJobReq)(nil), "model.UpdateJobReq")
	proto.RegisterType((*UpdateJobRes)(nil), "model.UpdateJobRes")
	proto.RegisterType((*ReadJobReq)(nil), "model.ReadJobReq")
	proto.RegisterType((*ReadJobRes)(nil), "model.ReadJobRes")
	proto.RegisterType((*DeleteJobReq)(nil), "model.DeleteJobReq")
	proto.RegisterType((*DeleteJobRes)(nil), "model.DeleteJobRes")
	proto.RegisterType((*ListJobsReq)(nil), "model.ListJobsReq")
	proto.RegisterType((*ListJobsRes)(nil), "model.ListJobsRes")
}

func init() { proto.RegisterFile("job.proto", fileDescriptor_f32c477d91a04ead) }

var fileDescriptor_f32c477d91a04ead = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0x0d, 0x05, 0x3e, 0x60, 0xe0, 0x33, 0x71, 0xf4, 0xd0, 0x34, 0xc4, 0x90, 0x9e, 0x88, 0x1a,
	0x34, 0xa8, 0xbf, 0x40, 0x4f, 0x8d, 0xa7, 0x1a, 0x7f, 0x40, 0xb7, 0x3b, 0x87, 0x25, 0xd0, 0x2d,
	0x9d, 0xaa, 0x7f, 0xc5, 0x9f, 0x6b, 0xba, 0x96, 0x75, 0x2d, 0x4d, 0x1a, 0x6f, 0x9d, 0xf7, 0xde,
	0xbc, 0x99, 0xbe, 0xc9, 0xc2, 0x64, 0xa3, 0xc5, 0x2a, 0x2f, 0x74, 0xa9, 0x71, 0xb8, 0xd3, 0x92,
	0xb6, 0x61, 0x02, 0xfd, 0x48, 0x0b, 0x3c, 0x01, 0x4f, 0x49, 0xbf, 0xb7, 0xe8, 0x2d, 0x27, 0xb1,
	0xa7, 0x24, 0x22, 0x0c, 0xb2, 0x64, 0x47, 0xbe, 0x67, 0x10, 0xf3, 0x8d, 0x0b, 0x98, 0x4a, 0xe2,
	0xb4, 0x50, 0x79, 0xa9, 0x74, 0xe6, 0xf7, 0x0d, 0xe5, 0x42, 0x78, 0x0e, 0x43, 0xfd, 0x91, 0x51,
	0xe1, 0x0f, 0x0c, 0xf7, 0x5d, 0x84, 0xd7, 0x30, 0x7b, 0x2c, 0x28, 0x29, 0x29, 0xd2, 0x22, 0xa6,
	0x3d, 0xce, 0xa1, 0xbf, 0xd1, 0xc2, 0x0c, 0x9b, 0xae, 0x61, 0x65, 0xf6, 0x58, 0x55, 0x5c, 0x05,
	0x37, 0xd4, 0xdc, 0xad, 0x7e, 0xcd, 0xe5, 0x1f, 0xbc, 0x1d, 0x75, 0x97, 0xf7, 0x1c, 0x20, 0xa6,
	0x44, 0xd6, 0xce, 0x8d, 0x84, 0xc2, 0x4b, 0x87, 0xed, 0x72, 0xba, 0x80, 0xd9, 0x13, 0x6d, 0xc9,
	0x6e, 0xd9, 0xf4, 0x5a, 0xfe, 0xe2, 0x19, 0x7d, 0x18, 0xf1, 0x5b, 0x9a, 0x12, 0xb3, 0x11, 0x8d,
	0xe3, 0x43, 0x19, 0xfe, 0x87, 0xe9, 0xb3, 0xe2, 0x32, 0xd2, 0x82, 0x63, 0xda, 0x87, 0x57, 0x6e,
	0xd9, 0xb1, 0xc5, 0xfa, 0xd3, 0x03, 0x88, 0xb4, 0x78, 0xa1, 0xe2, 0x5d, 0xa5, 0x84, 0x0f, 0x30,
	0xb1, 0x41, 0xe3, 0x59, 0x2d, 0x76, 0x0f, 0x15, 0xb4, 0x80, 0x8c, 0x37, 0x30, 0xaa, 0xff, 0x1b,
	0x4f, 0x6b, 0xfe, 0x27, 0xa5, 0xe0, 0x08, 0xe2, 0x6a, 0x8e, 0x0d, 0xdd, 0xce, 0x71, 0x8f, 0x16,
	0xb4, 0x80, 0xa6, 0xcd, 0x66, 0x62, 0xdb, 0xdc, 0x14, 0x83, 0x16, 0x90, 0xf1, 0x1e, 0xc6, 0x87,
	0x44, 0x10, 0x6b, 0x81, 0x93, 0x58, 0x70, 0x8c, 0xf1, 0x6d, 0x4f, 0xfc, 0x33, 0x6f, 0xe2, 0xee,
	0x2b, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x1e, 0x57, 0x17, 0x20, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JobServiceClient is the client API for JobService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobServiceClient interface {
	CreateJob(ctx context.Context, in *CreateJobReq, opts ...grpc.CallOption) (*CreateJobRes, error)
	ReadJob(ctx context.Context, in *ReadJobReq, opts ...grpc.CallOption) (*ReadJobRes, error)
	UpdateJob(ctx context.Context, in *UpdateJobReq, opts ...grpc.CallOption) (*UpdateJobRes, error)
	DeleteJob(ctx context.Context, in *DeleteJobReq, opts ...grpc.CallOption) (*DeleteJobRes, error)
	ListJobs(ctx context.Context, in *ListJobsReq, opts ...grpc.CallOption) (JobService_ListJobsClient, error)
}

type jobServiceClient struct {
	cc *grpc.ClientConn
}

func NewJobServiceClient(cc *grpc.ClientConn) JobServiceClient {
	return &jobServiceClient{cc}
}

func (c *jobServiceClient) CreateJob(ctx context.Context, in *CreateJobReq, opts ...grpc.CallOption) (*CreateJobRes, error) {
	out := new(CreateJobRes)
	err := c.cc.Invoke(ctx, "/model.JobService/CreateJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) ReadJob(ctx context.Context, in *ReadJobReq, opts ...grpc.CallOption) (*ReadJobRes, error) {
	out := new(ReadJobRes)
	err := c.cc.Invoke(ctx, "/model.JobService/ReadJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) UpdateJob(ctx context.Context, in *UpdateJobReq, opts ...grpc.CallOption) (*UpdateJobRes, error) {
	out := new(UpdateJobRes)
	err := c.cc.Invoke(ctx, "/model.JobService/UpdateJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) DeleteJob(ctx context.Context, in *DeleteJobReq, opts ...grpc.CallOption) (*DeleteJobRes, error) {
	out := new(DeleteJobRes)
	err := c.cc.Invoke(ctx, "/model.JobService/DeleteJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) ListJobs(ctx context.Context, in *ListJobsReq, opts ...grpc.CallOption) (JobService_ListJobsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_JobService_serviceDesc.Streams[0], "/model.JobService/ListJobs", opts...)
	if err != nil {
		return nil, err
	}
	x := &jobServiceListJobsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type JobService_ListJobsClient interface {
	Recv() (*ListJobsRes, error)
	grpc.ClientStream
}

type jobServiceListJobsClient struct {
	grpc.ClientStream
}

func (x *jobServiceListJobsClient) Recv() (*ListJobsRes, error) {
	m := new(ListJobsRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// JobServiceServer is the server API for JobService service.
type JobServiceServer interface {
	CreateJob(context.Context, *CreateJobReq) (*CreateJobRes, error)
	ReadJob(context.Context, *ReadJobReq) (*ReadJobRes, error)
	UpdateJob(context.Context, *UpdateJobReq) (*UpdateJobRes, error)
	DeleteJob(context.Context, *DeleteJobReq) (*DeleteJobRes, error)
	ListJobs(*ListJobsReq, JobService_ListJobsServer) error
}

func RegisterJobServiceServer(s *grpc.Server, srv JobServiceServer) {
	s.RegisterService(&_JobService_serviceDesc, srv)
}

func _JobService_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.JobService/CreateJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).CreateJob(ctx, req.(*CreateJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_ReadJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).ReadJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.JobService/ReadJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).ReadJob(ctx, req.(*ReadJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_UpdateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).UpdateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.JobService/UpdateJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).UpdateJob(ctx, req.(*UpdateJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_DeleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).DeleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.JobService/DeleteJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).DeleteJob(ctx, req.(*DeleteJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_ListJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListJobsReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobServiceServer).ListJobs(m, &jobServiceListJobsServer{stream})
}

type JobService_ListJobsServer interface {
	Send(*ListJobsRes) error
	grpc.ServerStream
}

type jobServiceListJobsServer struct {
	grpc.ServerStream
}

func (x *jobServiceListJobsServer) Send(m *ListJobsRes) error {
	return x.ServerStream.SendMsg(m)
}

var _JobService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.JobService",
	HandlerType: (*JobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJob",
			Handler:    _JobService_CreateJob_Handler,
		},
		{
			MethodName: "ReadJob",
			Handler:    _JobService_ReadJob_Handler,
		},
		{
			MethodName: "UpdateJob",
			Handler:    _JobService_UpdateJob_Handler,
		},
		{
			MethodName: "DeleteJob",
			Handler:    _JobService_DeleteJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListJobs",
			Handler:       _JobService_ListJobs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "job.proto",
}
